### ISSUE TITLE
Firefox 63: Shift+Tab doesn't work

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-control-state-mixin#46]
Can be reproduced on any `vaadin-control-state-mixin
`-dependent component, e.g. `vaadin-button`: https://cdn.vaadin.com/vaadin-button/2.1.0/demo/#button-basic-demos

**Comment by samiheikki** [comment]
To me shift+tab is working with Firefox 63 when you navigate from one `vaadin-button` to another.
But when you navigate to demo page's copy button the shift+tab is not working. I see the problem is more with the demo page than with `vaadin-control-state-mixin`.

Try tab and shift tab between the two vaadin-buttons in "Using an Icon" demo.

**Comment by samiheikki** [comment]
Created separate ticket (and fix) for copy button shift tab on Firefox 63: https://github.com/vaadin/vaadin-demo-helpers/issues/58

**Comment by tomivirkki** [comment]
Confirmed what Sami stated. I can change the component in the demo to a native `<input>` and shift-tab from the demo helper's "copy" -button still doesn't work. Closing this as it's not control state mixin related issue.
